[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run migrate && npm run start"
healthcheckPath = "/health"
healthcheckTimeout = 100

[build.environment]
NODE_VERSION = "20.18.0"
NPM_VERSION = "10.8.2"
